# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: 'npm' # See documentation for possible values
      directory: '/website/' # Location of package manifests
      target-branch: 'dev'
      schedule:
          interval: 'weekly'

    # Enable version updates for Cargo
    - package-ecosystem: 'cargo'
      # Look for a `Cargo.toml` in the `/backend/` directory
      directory: '/backend/'
      target-branch: 'dev'
      # Check for updates once a week
      schedule:
          interval: 'weekly'

    # Enable version updates for Docker in backend
    - package-ecosystem: 'docker'
      # Look for a `Dockerfile` in the `/backend/` directory
      directory: '/backend/'
      target-branch: 'dev'
      # Check for updates once a week
      schedule:
          interval: 'weekly'

    # Enable version updates for Docker in website
    - package-ecosystem: 'docker'
      # Look for a `Dockerfile` in the `/website/` directory
      directory: '/website/'
      target-branch: 'dev'
      # Check for updates once a week
      schedule:
          interval: 'weekly'
